version: "3.7"

services:
  application:
    build: .
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
    env_file:
      - api.env
    depends_on:
      - postgresql
      - redis


  postgresql:
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    image: postgres:15.0
    volumes:
      - postgresql-data:/var/lib/postgres
    env_file:
      - api.env
    command: -p ${POSTGRES_PORT}

  redis:
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    image: redis:6.2-alpine
    volumes:
      - cache:/data



volumes:
  postgresql-data:
  cache:
