version: "3.7"

services:
  application:
    build: .
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
    env_file:
      - api.env
    depends_on:
      - mongodb
      - redis
      - nats


  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - mongo-data:/data/db

  redis:
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    image: redis:6.2-alpine
    volumes:
      - cache:/data

  nats:
    image: nats
    ports:
      - ${NATS_PORT}:${NATS_PORT}
    healthcheck:
      test: ["CMD", "nats", "ping"]
      interval: 1s
      timeout: 1s
      retries: 5


volumes:
  mongo-data:
  cache:
