version: "3.7"

services:
  application:
    build: .
    ports:
      - "8080:8080"
      - "9091:9091"
    depends_on:
      mongodb:
        condition: service_started
      redis:
        condition: service_started
      nats:
        condition: service_started
      kafka-interview-planning:
        condition: service_started
      schema-registry-interview-planning:
        condition: service_started


  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: booking_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    ports:
      - "6379:6379"
    image: redis:6.2-alpine
    volumes:
      - cache:/data

  nats:
    image: nats
    ports:
      - "4222:4222"
    healthcheck:
      test: ["CMD", "nats", "ping"]
      interval: 1s
      timeout: 1s
      retries: 5

  kafka-interview-planning:
    image: confluentinc/cp-kafka:7.5.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: INTERNAL://kafka-interview-planning:29092, EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-interview-planning:29092, EXTERNAL://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-interview-planning:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, EXTERNAL:PLAINTEXT
    depends_on:
      - zookeeper-interview-planning
    volumes:
      - kafka-data:/var/lib/kafka/data

  zookeeper-interview-planning:
    image: confluentinc/cp-zookeeper:7.5.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log

  schema-registry-interview-planning:
    image: confluentinc/cp-schema-registry:7.5.1
    ports:
      - "8081:8081"
    depends_on:
      - kafka-interview-planning
      - zookeeper-interview-planning
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-interview-planning:29092

volumes:
  mongo-data:
  cache:
  kafka-data:
  zookeeper-data:
  zookeeper-log:
