server:
  port: 8080

jwt:
  secret: oneweek
  validity: 86400
  caching: 350

first-coordinator-email: guuzey2001@gmail.com

spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 240435898644410
            clientSecret: c47082928d4e274077cd1e2a56e1d7be
            redirectUri: https://localhost:8080/
  redis:
    host: localhost
    port: 6379

  data:
    mongodb:
      uri: mongodb://username:password@localhost:27017/booking_db?authSource=admin

nats:
  url: "nats://localhost:4222"
